CREATE USER ${username} IDENTIFIED BY ${password}
DEFAULT TABLESPACE ${database}
TEMPORARY TABLESPACE ${database}_temp
PROFILE ${planId};

GRANT CREATE SESSION, ALTER SESSION, CREATE DATABASE LINK,
CREATE MATERIALIZED VIEW, CREATE PROCEDURE, CREATE PUBLIC SYNONYM,
CREATE ROLE, CREATE SEQUENCE, CREATE SYNONYM, CREATE TABLE,
CREATE TRIGGER, CREATE TYPE, CREATE VIEW, UNLIMITED TABLESPACE, RESOURCE, CONNECT
to ${username};

COMMIT;